-- 코드를 입력하세요
SELECT DISTINCT a.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR as a
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY as b on a.CAR_ID = b.CAR_ID
WHERE a.CAR_TYPE = '세단' and MONTH(b.START_DATE) = '10'
ORDER BY CAR_ID DESC