SELECT
    a.APNT_NO,
    p.PT_NAME,
    p.PT_NO,
    a.MCDP_CD,
    d.DR_NAME,
    a.APNT_YMD
FROM
    APPOINTMENT a
    INNER JOIN DOCTOR d ON a.MDDR_ID = d.DR_ID
    INNER JOIN PATIENT p ON a.PT_NO = p.PT_NO
WHERE
    a.APNT_CNCL_YN = 'N'
    AND
    DATE_FORMAT(a.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
    AND
    a.MCDP_CD REGEXP 'CS'
ORDER BY
    a.APNT_YMD ASC;