-- 코드를 입력하세요
SELECT b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(b.PRICE * s.SALES) as TOTAL_SALES

FROM BOOK b
INNER JOIN AUTHOR a on b.AUTHOR_ID = a.AUTHOR_ID
INNER JOIN BOOK_SALES s on b.BOOK_ID = s.BOOK_ID

WHERE DATE_FORMAT(s.SALES_DATE, '%Y-%m-%d') LIKE '2022-01%'

GROUP BY b.AUTHOR_ID, b.CATEGORY

ORDER BY b.AUTHOR_ID , b.CATEGORY DESC