-- 코드를 작성해주세요
WITH RANKED_ECOLI AS (
    SELECT
        *,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS RANK_COLONY
    FROM ECOLI_DATA
) -- with함수를 통하여 필요한 테이블로만 작성

SELECT ID, CASE
    WHEN RANK_COLONY = 1 THEN 'CRITICAL'
    WHEN RANK_COLONY = 2 THEN 'HIGH'
    WHEN RANK_COLONY = 3 THEN 'MEDIUM'
    ELSE 'LOW'
END as COLONY_NAME
FROM RANKED_ECOLI
ORDER BY ID