-- 코드를 입력하세요
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (
         SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
         FROM ONLINE_SALE
    
         UNION ALL -- 온/오프라인 테이블 합치기
    
         SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
         FROM OFFLINE_SALE
     ) TABLE_SUM
WHERE SALES_DATE LIKE '2022-03%'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;