
-- 1. WITH 사용
WITH TOTAL AS (
    SELECT DISTINCT USER_ID
    FROM USER_INFO
    WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'
)

SELECT YEAR(SALES_DATE) AS 'YEAR'
      ,MONTH(SALES_DATE) AS 'MONTH'
      ,COUNT(DISTINCT USER_ID) AS PURCHASED_USERS
      ,ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(*) FROM TOTAL), 1) AS PURCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (
    SELECT *
    FROM TOTAL
)
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR ASC, MONTH ASC


-- 2. 사용 X

-- 코드를 입력하세요
SELECT 
YEAR(o.SALES_DATE) as YEAR,
MONTH(o.SALES_DATE) as MONTH,
COUNT(DISTINCT(o.USER_ID)) as PURCHASED_USERS,
ROUND(COUNT(DISTINCT(o.USER_ID)) / 
     (select count(*)
     from user_info
     where joined between '2021-01-01' and '2021-12-31'), 1
     ) as PUCHASED_RATIO
     
FROM USER_INFO u
JOIN ONLINE_SALE o on u.USER_ID = o.USER_ID

WHERE YEAR(u.JOINED) = '2021'

GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH