-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(a.PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD a
INNER JOIN USED_GOODS_USER b on a.WRITER_ID = b.USER_ID
WHERE a.STATUS = 'DONE'
GROUP BY b.USER_ID -- 왜? : USER_ID로 그룹화(이유 : 유저별로 판매금액을 더해야하기 때문)
HAVING SUM(a.PRICE) >= 700000
ORDER BY SUM(a.PRICE);