WITH HISTORY AS (
    SELECT *, DATEDIFF(END_DATE, START_DATE) + 1 AS DIFF ,CASE
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN "90일 이상"
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN "30일 이상"
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN "7일 이상"
    ELSE 0
    END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY)

SELECT H.HISTORY_ID,
    TRUNCATE(C.DAILY_FEE* IF(H.DURATION_TYPE = 0, 1, (100- D.DISCOUNT_RATE)*0.01) * H.DIFF,0) AS FEE 
FROM HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C
ON C.CAR_ID = H.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
ON H.DURATION_TYPE = D.DURATION_TYPE AND C.CAR_TYPE =D.CAR_TYPE
WHERE C.CAR_TYPE = "트럭"
GROUP BY H.HISTORY_ID
ORDER BY FEE DESC, H.HISTORY_ID DESC