-- 재귀 함수 사용해서 세대 구분
WITH RECURSIVE ECOLI AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL -- 1세대
    
    UNION ALL
    
    SELECT c.ID, c.PARENT_ID, (e.GENERATION + 1) AS GENERATION
    FROM ECOLI_DATA c, ECOLI e
    WHERE c.PARENT_ID = e.ID -- 2세대, 3세대, 4세대 
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM ECOLI
WHERE ID NOT IN (SELECT PARENT_ID FROM ECOLI WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION