-- 코드를 입력하세요
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_INS I
RIGHT JOIN ANIMAL_OUTS O on I.ANIMAL_ID = O.ANIMAL_ID 
-- OUT 테이블에 기준에 맞춰 RIGHT 조인 후, INS 테이블이 null인걸 조회
WHERE I.ANIMAL_ID is NULL
ORDER BY O.ANIMAL_ID